gremlin-client/src/conversion.rs
Simple PR, but I though you would appreciate. Found this while looking through your code. Thanks for working on this project. I hope to be able to contribute more in the future.
=> Fix typo in macro definition

gremlin-client/src/lib.rs, gremlin-client/src/process/traversal/graph_traversal_source.rs
This PR makes the `withSideEffect` functionality possible. This can be used on Neptune do stuff such as: https://docs.aws.amazon.com/neptune/latest/userguide/gremlin-query-hints-repeatMode.html. 
I couldn't figure out what kind of test to write that would work against a normal Tinkerpop server. I have tested this against Neptune and all works well. I can see uses of the function in the Tinkerpop documentation but the other methods in order to implement them are not implemented in gremlin-rs. (see: http://tinkerpop.apache.org/docs/current/reference/#where-step).
FromGValue also made public so that user made functions can be created with generic trait parameter `E: FromGValue` for passing around `GraphTraversal`.
=> Implements basic with_side_effect on GraphTraversalSource

gremlin-client/src/io/mod.rs, gremlin-client/src/lib.rs, gremlin-client/src/process/traversal/builder.rs, gremlin-client/src/process/traversal/graph_traversal.rs, gremlin-client/src/structure/cardinality.rs, gremlin-client/src/structure/label.rs, gremlin-client/src/structure/mod.rs, gremlin-client/src/structure/value.rs, gremlin-client/tests/integration_traversal.rs
Added two new functions on GraphTraversal - `property_with_cardinality()` and `property_many_with_cardinality()`. 
I wanted to implement cardinality on new functions as otherwise the `.property()` input would have to be converted into a tuple. Meaning all existing implementation of `.property()` made by people would have to be migrated over to use tuples.
If you would prefer to implement this within .property I can do that instead - just let me know.
=> Added sending property cardinality with two new functions

gremlin-client/src/aio/client.rs, gremlin-client/src/lib.rs, gremlin-client/src/process/traversal/anonymous_traversal_source.rs, gremlin-client/src/process/traversal/builder.rs, gremlin-client/src/process/traversal/bytecode.rs, gremlin-client/src/process/traversal/graph_traversal.rs, gremlin-client/src/process/traversal/mod.rs, gremlin-client/src/process/traversal/remote.rs, gremlin-client/src/structure/either.rs
This PR implements the following:
- `.project()`,  `.constant()` & `.barrier()` steps on Traversal's
- New `.empty()` on `RemoteTraversalSource` allows for init and building of traversal before deciding which remote to send requests to
- `.does_write()` method on `GraphTraversal`. Allows for determining if a traversal does some write operation and then sending to a gremlin server which is used for write operations. This is handy in AWS Neptune where you have one write database and the possibility of several read replicas.
- New `.changeRemote()` method on `GraphTraversal`
Sorry no tests yet, but all methods are operating as expected in my application
=> Some more features

gremlin-client/src/io/macros.rs
This change should close #97.  It looks like the problem was in the deserialization path. The query was returning a vertex property with a boolean property.  Or rather more, precisely, property that was a g:List of booleans. The deserializer was correctly identifying the list and passing it to deserialize_list, which then called reader on the first and only element of the list, which was a serialized boolean. The g_serializer macro was unequipped to handle a boolean result, though.
Admittedly, what I don't understand is why the Gremlin server was passing back the property value in the array as a straight serialized boolean.  When I make the same query passing an integer instead of a boolean, it comes back as an object in the array, with a type and value separately:
```
Object({
"@type": …
```
=> Closes #97.

gremlin-client/src/client.rs, gremlin-client/src/lib.rs, gremlin-client/src/process/traversal/anonymous_traversal_source.rs, gremlin-client/src/process/traversal/builder.rs, gremlin-client/src/process/traversal/graph_traversal.rs
Found it useful to have a function exposed where I could leverage the bytecode generation built into gremlin-rs; hence I added `generate_message()`. Allowed me to write some queries in gremlin-rs and then have the bytecode available to send to some other endpoint for further analysis or persistence.
=> Adds repeat, until & emit functionality on GraphTraversal & AnonGraphTraversal + expose fn to get generated bytecode

gremlin-client/src/aio/process/traversal/mod.rs
=> Expose `AsyncTerminator` publicly

.gitignore, docker-compose/version-3/gremlin-server-v3.yaml, gremlin-client/src/aio/client.rs, gremlin-client/src/client.rs, gremlin-client/tests/integration_client.rs, gremlin-client/tests/integration_client_async.rs
This PR provides an initial implementation of session support. If merged, it should close #113.
- The change adds two functions, `openSession` and `closeSession` to the `GremlinClient`, both synchronous and asynchronous.
- Internally, the `openSession` function creates a new pool with just a single connection for the session, along with tracking the session name, which the client of the library will most often set to the `String` representation of a UUID. An alternative would've been to just create a single `Connection` rather than a pool of 1, but using the pool allowed for greater re-use of existing functions without changes, because many of the functions involved in sending messages take a managed connection from the pool.
- Queries that are sent using `execute` are sent to the session …
=> Session support

gremlin-client/src/io/mod.rs, gremlin-client/src/io/serializer_v2.rs, gremlin-client/src/io/serializer_v3.rs, gremlin-client/tests/integration_client.rs, gremlin-client/tests/integration_client_v1.rs, gremlin-client/tests/integration_client_v2.rs
Closes #128 
This PR is a breaking change upon dates that are currently serialized since they would be serialized as epoch seconds not epoch milliseconds, but the Tinkerpop standard for [version 2](http://tinkerpop.apache.org/docs/current/dev/io/#_date) and [version 3](http://tinkerpop.apache.org/docs/current/dev/io/#_date_2) expects milliseconds.
Given the library is still major version 0 such breaking changes are permitted per semver expectations, but wanted to call it out for your consideration when reviewing.
=> Fixed precision of g:Date values to milliseconds

gremlin-client/src/structure/value.rs, gremlin-client/tests/integration_client.rs
=> Fixed / Added Option support for: String, i32, i64, f32, f64, uuid, date, and bool

gremlin-client/src/aio/client.rs, gremlin-client/src/client.rs, gremlin-client/tests/integration_client.rs, gremlin-client/tests/integration_client_async.rs
@wolf4ood, it looks like I missed something when I submitted the contribution for sessions a while back. There's some additional code necessary to allow the client to gracefully close sessions. Absent that, it leaves them hanging, which has different (and sometimes poor) behavior across different Gremlin-speaking servers.  This PR adds a `close_session` function that properly closes down a `SessionedClient`.
=> Close session

gremlin-client/src/aio/mod.rs
As mentioned in https://github.com/wolf4ood/gremlin-rs/pull/123 it seems there needs to be a little more to fully expose `AsyncTerminator`. @wolf4ood for your review at your convenience.
=> Expose AsyncTerminator as gremlin::client::aio:AsyncTerminator

gremlin-client/src/error.rs, gremlin-client/src/structure/list.rs, gremlin-client/src/structure/map.rs, gremlin-client/src/structure/set.rs, gremlin-client/src/structure/value.rs
As I'm working with gremlin-rs, I've noticed that I had to write a handful of helper functions to shuffle collections from `GValue` types back and forth with standard library collection types based on `Vec` and `HashMap`.  This pull request proposes to add a few more `From` and `TryFrom` implementations to `gremlin-rs` types as a convenience feature.
=> Collection Type Conversions

README.md, gremlin-client/src/process/traversal/builder.rs, gremlin-client/src/process/traversal/graph_traversal.rs, gremlin-client/src/process/traversal/graph_traversal_source.rs, gremlin-client/tests/integration_traversal.rs, gremlin-client/tests/integration_traversal_v2.rs
Adds support for the elementMap step from TinkerPop 3.4.4+
https://tinkerpop.apache.org/docs/current/reference/#elementmap-step
=> Add elementMap step

gremlin-client/src/io/macros.rs
When using gremlin-client witha somewhat recent rustc, we get a lot of warnings about the extra `;` in macros.rs.
This fixes it and should affect anything.
=> Remove noisy rustc warnings

gremlin-client/Cargo.toml, gremlin-client/src/connection.rs, gremlin-client/src/error.rs
I encountered a dependency issue due to the age of dependencies brought in through the websocket-rs crate and this crate's inclusion of `time` through `chrono`.
The websocket-rs crate is bringing a very old version of [hyper](https://github.com/websockets-rs/rust-websocket/blob/74c82be3de282e1c4c35c51daac1a84b583ce8ea/Cargo.toml#L20) and the time crate has a [known issue](https://github.com/time-rs/time/issues/293) but setting the feature flags as done in this PR avoids the issue.
I swapped the websocket-rs crate with using tungstenite which is one of the suggestions listed by websocket-rs and also because this crate already used async-tungstenite.
@wolf4ood if this is acceptable to you mind cutting a new release after its merged?
=> Remove Websocket & Time crates

gremlin-client/src/process/traversal/builder.rs
I noticed `.e()` is not available on `TraversalBuilder` - this patch adds it.
(I prefer to separate traversal building from the client instance, so that's why I usually use `TraversalBuilder` directly).
=> Add .e traversal step to TraversalBuilder

gremlin-client/src/structure/value.rs
This facilitates things like executing gremlin `propertyMap` and then handling the results with `FromGMap`.
=> Support Property/VertexProperty in TryFrom<GValue>

gremlin-client/src/process/traversal/builder.rs
Adds the `.id()` step as documented [here](https://tinkerpop.apache.org/docs/current/reference/#id-step).
=> Add .id() step to the traversal builder

gremlin-client/src/aio/connection.rs, gremlin-client/src/connection.rs, gremlin-client/src/lib.rs
Hey @wolf4ood I bumped into what seems to be an implicit default that wasn't exposed by this crate. These functions:
https://github.com/wolf4ood/gremlin-rs/blob/master/gremlin-client/src/connection.rs#L51
https://github.com/wolf4ood/gremlin-rs/blob/master/gremlin-client/src/aio/connection.rs#L133-L136
Appeared to be leveraging `tungstenite`'s default websocket settings by using the method that didn't specify a websocket config:
https://github.com/snapview/tungstenite-rs/blob/371f8230444e209cc37ec481e94d621eddf5f0af/src/tls.rs#L180
https://github.com/sdroege/async-tungstenite/blob/2365647978412f47e681d498f25b8469f4355f11/src/tokio.rs#L267
This `None` then becomes the defaults defined by `tungstenite`: https://github.com/snapview/tungstenite-rs/blob/master/src/protocol/mod.rs#L39-L70
I was …
=> Exposed websocket max_message_size  through ConnectionOptions

gremlin-client/src/error.rs
Fixes `the trait From<tungstenite::Error> is not implemented for GremlinError` with non async features.
I'm not sure this is the right way to solve the problem.
=> Fix From<tungstenite::Error> for non async_gremlin features

gremlin-client/src/aio/client.rs, gremlin-client/src/client.rs, gremlin-client/src/connection.rs
I was periodically encountering my applications effectively locking up because of Errors stating `Async pool timeout` . In my use case I'd rather just wait indefinitely for a connection to be available throughout my application. Prior to this PR `gremlin-rs` was relying on the default pool connection timeout of 30 seconds, coincidentally the same for both the sync pool (r2d2) and the async pool (mobc) providers.
This PR will allow users of the library to modify the timeout, and possibly, for the async pool, opt out of a timeout all together.
@wolf4ood jumped to a PR, but happy to open an issue if you'd like to talk & refine the idea further. If it looks good to you as is mind cutting another release once it's merged?
=> Expose connection pool's get timeout via ConnectionOptionsBuilder
